# Generated by Django 4.2.8 on 2023-12-21 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppealType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appeal_type', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Appeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('phone', models.CharField(max_length=70)),
                ('lang', models.CharField(max_length=30)),
                ('at_time', models.DateTimeField()),
                ('more_about_time', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('appeal_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type', to='appeal.appealtype')),
            ],
        ),
    ]
