# Generated by Django 4.2.8 on 2023-12-21 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appeal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appeal',
            name='appeal_type_id',
        ),
    ]
