
version: '3'

services:
  api:
    build: .
    command: >
      sh -c "gunicorn core.wsgi:application --bind 0.0.0.0:8000"
    ports:
      - '8000:8000'
    restart: always
    depends_on:
      - postgres
      - migration
    volumes:
      - .:/app
      - static_volume:/usr/src/app/static
    environment:
      - VIRTUAL_HOST=gulsdem.pp.ua
      - LETSENCRYPT_HOST=gulsdem.pp.ua

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: alkhail_user
      POSTGRES_PASSWORD: 1
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - '5432:5432'

  migration:
    build: .
    command: sh -c "python3 manage.py makemigrations && python3 manage.py migrate"
    volumes:
      - .:/usr/src/app
    depends_on:
      - postgres

#  adminer:
#    image: adminer
#    restart: always
#    ports:
#      - '8888:8080'

  nginx:
    image: nginx:latest
    container_name: docker_nginx-1
    ports:
      - "80:80"
      - "443-443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/usr/src/app/back_static
      - media_volume:/usr/src/app/back_media
    depends_on:
      - api

  redis:
    image: redis
    ports:
      - "6379:6379"

  celery:
    build: .
    command: celery -A core worker -l INFO

    volumes:
      - .:/usr/src/app/
    depends_on:
      - api
      - redis

volumes:
  postgres_data:
  static_volume:
  media_volume: