
version: '3'

services:
  api:
    build: .
    command: >
      sh -c "gunicorn core.wsgi:application --bind 0.0.0.0:8000"
    ports:
      - '8000:8000'
    restart: always
    depends_on:
      - postgres
      - migration
    volumes:
      - .:/app
      - static_volume:/usr/src/app/static
      - media_volume:/usr/src/app/back_media
    environment:
      - VIRTUAL_HOST=alkhail.pp.ua
      - LETSENCRYPT_HOST=alkhail.pp.ua

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  migration:
    build: .
    command: sh -c "python3 manage.py makemigrations && python3 manage.py migrate"
    volumes:
      - .:/usr/src/app
    depends_on:
      - postgres

  nginx:
    image: nginx:latest
    container_name: docker_nginx-1
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
#      - ./nginx/alt.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/usr/src/app/static
      - media_volume:/usr/src/app/back_media
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d
      - certs:/etc/nginx/certs
    depends_on:
      - api

  redis:
    image: redis
    ports:
      - "6379:6379"

  celery:
    build: .
    command: celery -A core worker -l INFO

    volumes:
      - .:/usr/src/app/
    depends_on:
      - api
      - redis

  acme_companion:
    image: nginxproxy/acme-companion:2.2
    container_name: acme_companion
    volumes_from:
    - nginx
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - acme:/etc/acme.sh

volumes:
  postgres_data:
  static_volume:
  media_volume:
  certs:
  acme:
  vhost:
  html: