# Generated by Django 4.2.8 on 2024-01-15 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_for_purchase', models.BooleanField(verbose_name='Want to buy')),
                ('name', models.CharField(max_length=70, verbose_name='Name')),
                ('phone', models.CharField(max_length=70, verbose_name='Phone number')),
                ('lang', models.CharField(max_length=30, verbose_name='Message Language')),
                ('at_time', models.DateTimeField(null=True, verbose_name='Call at time')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Send date')),
                ('is_send', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Message from site',
                'verbose_name_plural': 'Messages from site',
            },
        ),
    ]
