# Generated by Django 4.2.8 on 2023-12-25 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estate', '0002_remove_estate_currency_remove_estate_currency_ar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_for_purchase', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=70)),
                ('phone', models.CharField(max_length=70)),
                ('lang', models.CharField(max_length=30)),
                ('at_time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('estate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appel', to='estate.estate')),
            ],
        ),
    ]
