# Generated by Django 4.2.8 on 2023-12-30 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appeal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appeal',
            options={'verbose_name': 'Message from site', 'verbose_name_plural': 'Messages from site'},
        ),
        migrations.AlterField(
            model_name='appeal',
            name='at_time',
            field=models.DateTimeField(verbose_name='Call at time'),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Send date'),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='is_for_purchase',
            field=models.BooleanField(default=True, verbose_name='Want to buy'),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='lang',
            field=models.CharField(max_length=30, verbose_name='Message Language'),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='name',
            field=models.CharField(max_length=70, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='phone',
            field=models.CharField(max_length=70, verbose_name='Phone number'),
        ),
    ]
