# Generated by Django 4.2.8 on 2023-12-26 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0002_remove_estate_currency_remove_estate_currency_ar_and_more'),
        ('appeal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appeal',
            name='estate_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estate', to='estate.estate'),
        ),
    ]
