# Generated by Django 4.2.8 on 2023-12-30 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appeal', '0003_alter_appeal_at_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appeal',
            name='at_time',
            field=models.DateTimeField(null=True, verbose_name='Call at time'),
        ),
    ]
