# Generated by Django 4.2.8 on 2023-12-30 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0003_alter_estate_create_at_alter_estate_description_and_more'),
        ('appeal', '0004_alter_appeal_at_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appeal',
            name='estate_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appel', to='estate.estate'),
        ),
    ]
