# Generated by Django 4.2.8 on 2024-01-06 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staticdata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticdata',
            name='default_image',
            field=models.ImageField(default=1, upload_to='default_image/', verbose_name='default image path'),
            preserve_default=False,
        ),
    ]
