# Generated by Django 4.2.8 on 2023-12-21 13:37

import city.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=255)),
                ('city_name_en', models.CharField(max_length=255, null=True)),
                ('city_name_ar', models.CharField(max_length=255, null=True)),
                ('city_name_tr', models.CharField(max_length=255, null=True)),
                ('city_name_ru', models.CharField(max_length=255, null=True)),
                ('city_description', models.TextField()),
                ('city_description_en', models.TextField(null=True)),
                ('city_description_ar', models.TextField(null=True)),
                ('city_description_tr', models.TextField(null=True)),
                ('city_description_ru', models.TextField(null=True)),
                ('city_img', models.ImageField(upload_to=city.models.City.upload_to)),
            ],
        ),
    ]
