# Generated by Django 4.2.8 on 2024-02-14 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50, verbose_name='Company name')),
                ('mission', models.TextField(verbose_name='Company mission')),
                ('mission_en', models.TextField(null=True, verbose_name='Company mission')),
                ('mission_ar', models.TextField(null=True, verbose_name='Company mission')),
                ('mission_tr', models.TextField(null=True, verbose_name='Company mission')),
                ('mission_ru', models.TextField(null=True, verbose_name='Company mission')),
                ('history', models.TextField(verbose_name='Company history')),
                ('history_en', models.TextField(null=True, verbose_name='Company history')),
                ('history_ar', models.TextField(null=True, verbose_name='Company history')),
                ('history_tr', models.TextField(null=True, verbose_name='Company history')),
                ('history_ru', models.TextField(null=True, verbose_name='Company history')),
                ('company', models.TextField(verbose_name='About company')),
                ('company_en', models.TextField(null=True, verbose_name='About company')),
                ('company_ar', models.TextField(null=True, verbose_name='About company')),
                ('company_tr', models.TextField(null=True, verbose_name='About company')),
                ('company_ru', models.TextField(null=True, verbose_name='About company')),
                ('phone', models.CharField(max_length=150, verbose_name='Phone number')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('company_img', models.ImageField(upload_to='company/', verbose_name='Company logo path')),
            ],
            options={
                'verbose_name_plural': 'About company',
            },
        ),
    ]
