# Generated by Django 4.2.8 on 2023-12-24 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('company_name_en', models.CharField(max_length=50, null=True)),
                ('company_name_ar', models.CharField(max_length=50, null=True)),
                ('company_name_tr', models.CharField(max_length=50, null=True)),
                ('company_name_ru', models.CharField(max_length=50, null=True)),
                ('about', models.TextField()),
                ('about_en', models.TextField(null=True)),
                ('about_ar', models.TextField(null=True)),
                ('about_tr', models.TextField(null=True)),
                ('about_ru', models.TextField(null=True)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('company_img', models.ImageField(upload_to='company/')),
            ],
        ),
    ]
