# Generated by Django 4.2.8 on 2023-12-30 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'About company'},
        ),
        migrations.AlterField(
            model_name='company',
            name='about',
            field=models.TextField(verbose_name='About company'),
        ),
        migrations.AlterField(
            model_name='company',
            name='about_ar',
            field=models.TextField(null=True, verbose_name='About company'),
        ),
        migrations.AlterField(
            model_name='company',
            name='about_en',
            field=models.TextField(null=True, verbose_name='About company'),
        ),
        migrations.AlterField(
            model_name='company',
            name='about_ru',
            field=models.TextField(null=True, verbose_name='About company'),
        ),
        migrations.AlterField(
            model_name='company',
            name='about_tr',
            field=models.TextField(null=True, verbose_name='About company'),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_img',
            field=models.ImageField(upload_to='company/', verbose_name='Company photo/logo'),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_name',
            field=models.CharField(max_length=50, verbose_name='Company name'),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_name_ar',
            field=models.CharField(max_length=50, null=True, verbose_name='Company name'),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_name_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Company name'),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_name_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Company name'),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_name_tr',
            field=models.CharField(max_length=50, null=True, verbose_name='Company name'),
        ),
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.CharField(max_length=15, verbose_name='Phone number'),
        ),
    ]
