# Generated by Django 4.2.8 on 2024-01-06 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_company_options_alter_company_about_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_img',
            field=models.ImageField(upload_to='company/', verbose_name='Company photo path'),
        ),
    ]
