# Generated by Django 4.2.8 on 2024-01-20 10:46

import apps.project.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, unique=True, verbose_name='Type of facilities')),
                ('type_en', models.CharField(max_length=50, null=True, unique=True, verbose_name='Type of facilities')),
                ('type_ar', models.CharField(max_length=50, null=True, unique=True, verbose_name='Type of facilities')),
                ('type_tr', models.CharField(max_length=50, null=True, unique=True, verbose_name='Type of facilities')),
                ('type_ru', models.CharField(max_length=50, null=True, unique=True, verbose_name='Type of facilities')),
                ('icon', models.ImageField(blank=True, null=True, upload_to=apps.project.models.Facilities.icon_upload, verbose_name='Icon path')),
            ],
            options={
                'verbose_name': 'Facilities Type',
                'verbose_name_plural': 'Facilities Types',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Project name [En]')),
                ('location', models.CharField(max_length=100, verbose_name='Location [En]')),
                ('developer', models.CharField(blank=True, max_length=100, null=True, verbose_name='Developer [En]')),
                ('completion', models.DateField(blank=True, null=True, verbose_name='Completion date')),
                ('is_furnished', models.BooleanField(verbose_name='With furniture')),
                ('pdf_catalog', models.FileField(upload_to=apps.project.models.Project.project_upload, verbose_name='PDF catalog path')),
                ('facilities', models.ManyToManyField(related_name='project', to='project.facilities', verbose_name='Project facilities')),
            ],
        ),
    ]
