<<<<<<< HEAD
# Generated by Django 4.2.8 on 2024-01-11 19:13
=======
# Generated by Django 4.2.8 on 2024-01-10 13:07
>>>>>>> dbf23d998b2d378b3dc86440301fb30a88e5c906

import apps.estate.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('city', '0004_alter_city_city_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('title', models.CharField(max_length=100, verbose_name='Estate title')),
                ('title_en', models.CharField(max_length=100, null=True, verbose_name='Estate title')),
                ('title_ar', models.CharField(max_length=100, null=True, verbose_name='Estate title')),
                ('title_tr', models.CharField(max_length=100, null=True, verbose_name='Estate title')),
                ('title_ru', models.CharField(max_length=100, null=True, verbose_name='Estate title')),
=======
                ('name', models.CharField(max_length=100, verbose_name='estate_name')),
                ('name_en', models.CharField(max_length=100, null=True, verbose_name='estate_name')),
                ('name_ar', models.CharField(max_length=100, null=True, verbose_name='estate_name')),
                ('name_tr', models.CharField(max_length=100, null=True, verbose_name='estate_name')),
                ('name_ru', models.CharField(max_length=100, null=True, verbose_name='estate_name')),
>>>>>>> dbf23d998b2d378b3dc86440301fb30a88e5c906
                ('developer', models.CharField(max_length=100, verbose_name='Developer')),
                ('developer_en', models.CharField(max_length=100, null=True, verbose_name='Developer')),
                ('developer_ar', models.CharField(max_length=100, null=True, verbose_name='Developer')),
                ('developer_tr', models.CharField(max_length=100, null=True, verbose_name='Developer')),
                ('developer_ru', models.CharField(max_length=100, null=True, verbose_name='Developer')),
<<<<<<< HEAD
=======
                ('area', models.FloatField(verbose_name='estate_area')),
>>>>>>> dbf23d998b2d378b3dc86440301fb30a88e5c906
                ('district', models.CharField(max_length=100, verbose_name='District')),
                ('district_en', models.CharField(max_length=100, null=True, verbose_name='District')),
                ('district_ar', models.CharField(max_length=100, null=True, verbose_name='District')),
                ('district_tr', models.CharField(max_length=100, null=True, verbose_name='District')),
                ('district_ru', models.CharField(max_length=100, null=True, verbose_name='District')),
<<<<<<< HEAD
                ('area', models.FloatField(verbose_name='Area (m2)')),
=======
>>>>>>> dbf23d998b2d378b3dc86440301fb30a88e5c906
                ('description', models.TextField(max_length=500, verbose_name='Description')),
                ('description_en', models.TextField(max_length=500, null=True, verbose_name='Description')),
                ('description_ar', models.TextField(max_length=500, null=True, verbose_name='Description')),
                ('description_tr', models.TextField(max_length=500, null=True, verbose_name='Description')),
                ('description_ru', models.TextField(max_length=500, null=True, verbose_name='Description')),
                ('is_secondary', models.BooleanField(default=True, verbose_name='Secondary estate')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Create date')),
<<<<<<< HEAD
                ('visits', models.IntegerField(default=0, verbose_name='Visits')),
=======
>>>>>>> dbf23d998b2d378b3dc86440301fb30a88e5c906
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='estate', to='city.city')),
            ],
        ),
        migrations.CreateModel(
            name='EstateType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30, verbose_name='Estate Type')),
                ('type_en', models.CharField(max_length=30, null=True, verbose_name='Estate Type')),
                ('type_ar', models.CharField(max_length=30, null=True, verbose_name='Estate Type')),
                ('type_tr', models.CharField(max_length=30, null=True, verbose_name='Estate Type')),
                ('type_ru', models.CharField(max_length=30, null=True, verbose_name='Estate Type')),
<<<<<<< HEAD
            ],
            options={
                'verbose_name': 'Estate Type',
                'verbose_name_plural': 'Estate Types',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Project name')),
                ('name_en', models.CharField(max_length=100, null=True, verbose_name='Project name')),
                ('name_ar', models.CharField(max_length=100, null=True, verbose_name='Project name')),
                ('name_tr', models.CharField(max_length=100, null=True, verbose_name='Project name')),
                ('name_ru', models.CharField(max_length=100, null=True, verbose_name='Project name')),
                ('pdf_catalog', models.FileField(upload_to='catalog/', verbose_name='PDF catalog path')),
=======
>>>>>>> dbf23d998b2d378b3dc86440301fb30a88e5c906
            ],
            options={
                'verbose_name': 'Estate Type',
                'verbose_name_plural': 'Estate Types',
            },
        ),
        migrations.CreateModel(
            name='EstateImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to=apps.estate.models.EstateImage.upload_to)),
                ('estate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='estate.estate')),
            ],
        ),
        migrations.AddField(
            model_name='estate',
            name='estate_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='estate', to='estate.estatetype'),
        ),
        migrations.AddField(
            model_name='estate',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estate', to='estate.project', verbose_name='Project'),
        ),
    ]
