# Generated by Django 4.2.8 on 2024-01-11 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='name_ar',
        ),
        migrations.RemoveField(
            model_name='project',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='project',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='project',
            name='name_tr',
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Project'),
        ),
    ]
