# Generated by Django 4.2.8 on 2023-12-24 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estate',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='estate',
            name='currency_ar',
        ),
        migrations.RemoveField(
            model_name='estate',
            name='currency_en',
        ),
        migrations.RemoveField(
            model_name='estate',
            name='currency_ru',
        ),
        migrations.RemoveField(
            model_name='estate',
            name='currency_tr',
        ),
        migrations.RemoveField(
            model_name='estate',
            name='pdf_cataloge',
        ),
        migrations.RemoveField(
            model_name='estate',
            name='price',
        ),
        migrations.RemoveField(
            model_name='estate',
            name='price_ar',
        ),
        migrations.RemoveField(
            model_name='estate',
            name='price_en',
        ),
        migrations.RemoveField(
            model_name='estate',
            name='price_ru',
        ),
        migrations.RemoveField(
            model_name='estate',
            name='price_tr',
        ),
        migrations.RemoveField(
            model_name='estate',
            name='update_at',
        ),
        migrations.RemoveField(
            model_name='estate',
            name='vizits',
        ),
    ]
