# Generated by Django 4.2.8 on 2023-12-30 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0002_remove_estate_currency_remove_estate_currency_ar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estate',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Create date'),
        ),
        migrations.AlterField(
            model_name='estate',
            name='description',
            field=models.TextField(max_length=500, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='estate',
            name='description_ar',
            field=models.TextField(max_length=500, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='estate',
            name='description_en',
            field=models.TextField(max_length=500, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='estate',
            name='description_ru',
            field=models.TextField(max_length=500, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='estate',
            name='description_tr',
            field=models.TextField(max_length=500, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='estate',
            name='developer',
            field=models.CharField(max_length=100, verbose_name='Developer'),
        ),
        migrations.AlterField(
            model_name='estate',
            name='developer_ar',
            field=models.CharField(max_length=100, null=True, verbose_name='Developer'),
        ),
        migrations.AlterField(
            model_name='estate',
            name='developer_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Developer'),
        ),
        migrations.AlterField(
            model_name='estate',
            name='developer_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Developer'),
        ),
        migrations.AlterField(
            model_name='estate',
            name='developer_tr',
            field=models.CharField(max_length=100, null=True, verbose_name='Developer'),
        ),
        migrations.AlterField(
            model_name='estate',
            name='district',
            field=models.CharField(max_length=100, verbose_name='District'),
        ),
        migrations.AlterField(
            model_name='estate',
            name='district_ar',
            field=models.CharField(max_length=100, null=True, verbose_name='District'),
        ),
        migrations.AlterField(
            model_name='estate',
            name='district_en',
            field=models.CharField(max_length=100, null=True, verbose_name='District'),
        ),
        migrations.AlterField(
            model_name='estate',
            name='district_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='District'),
        ),
        migrations.AlterField(
            model_name='estate',
            name='district_tr',
            field=models.CharField(max_length=100, null=True, verbose_name='District'),
        ),
        migrations.AlterField(
            model_name='estate',
            name='is_secondary',
            field=models.BooleanField(default=True, verbose_name='Secondary estate'),
        ),
        migrations.AlterField(
            model_name='estatetype',
            name='type',
            field=models.CharField(max_length=30, verbose_name='Estate Type'),
        ),
        migrations.AlterField(
            model_name='estatetype',
            name='type_ar',
            field=models.CharField(max_length=30, null=True, verbose_name='Estate Type'),
        ),
        migrations.AlterField(
            model_name='estatetype',
            name='type_en',
            field=models.CharField(max_length=30, null=True, verbose_name='Estate Type'),
        ),
        migrations.AlterField(
            model_name='estatetype',
            name='type_ru',
            field=models.CharField(max_length=30, null=True, verbose_name='Estate Type'),
        ),
        migrations.AlterField(
            model_name='estatetype',
            name='type_tr',
            field=models.CharField(max_length=30, null=True, verbose_name='Estate Type'),
        ),
    ]
