# Generated by Django 4.2.8 on 2024-01-06 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0003_alter_estate_create_at_alter_estate_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estatetype',
            options={'verbose_name': 'Estate Type', 'verbose_name_plural': 'Estate Types'},
        ),
    ]
