# Generated by Django 4.2.8 on 2023-12-20 20:08

from django.db import migrations, models
import django.db.models.deletion
import estate.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=255)),
                ('city_description', models.TextField()),
                ('city_img', models.ImageField(upload_to='media/city/')),
            ],
        ),
        migrations.CreateModel(
            name='Estate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='estate_name')),
                ('developer', models.CharField(max_length=100, verbose_name='estate_developer')),
                ('area', models.FloatField(verbose_name='estate_area')),
                ('district', models.CharField(max_length=100, verbose_name='estate_district')),
                ('description', models.TextField(max_length=500, verbose_name='estate_description')),
                ('is_secondary', models.BooleanField(default=True, verbose_name='estate_is_secondary')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='estate', to='estate.city')),
            ],
        ),
        migrations.CreateModel(
            name='EstateType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='EstateImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to=estate.models.EstateImage.upload_to)),
                ('estate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='estate.estate')),
            ],
        ),
        migrations.AddField(
            model_name='estate',
            name='estate_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='estate', to='estate.estatetype'),
        ),
    ]
