# Generated by Django 4.2.8 on 2024-01-26 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogdownloader',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='catalogdownloader',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='catalogdownloader',
            name='phone',
            field=models.CharField(max_length=100, verbose_name='Phone number'),
        ),
        migrations.AlterField(
            model_name='catalogdownloader',
            name='role',
            field=models.CharField(max_length=30),
        ),
    ]
