# Generated by Django 4.2.8 on 2024-02-08 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='at_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
