# Generated by Django 4.2.8 on 2024-01-22 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadcatalog',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
