# Generated by Django 4.2.8 on 2024-02-02 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='downloadcatalog',
            old_name='phone_number',
            new_name='phone',
        ),
    ]
