# Generated by Django 4.2.8 on 2024-02-10 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appeal',
            name='at_date',
            field=models.DateField(null=True, verbose_name='Call at time'),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='city',
            field=models.CharField(max_length=100, verbose_name='Respondent city'),
        ),
    ]
