# Generated by Django 4.2.8 on 2024-01-20 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analytics',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.role'),
        ),
        migrations.AlterField(
            model_name='role',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True),
        ),
    ]
