# Generated by Django 4.2.8 on 2024-02-11 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0001_initial'),
        ('analytics', '0002_appeal_at_date_alter_appeal_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appeal',
            name='is_for_purchase',
        ),
        migrations.AddField(
            model_name='appeal',
            name='appeal_type',
            field=models.CharField(choices=[('purchase', 'Purchase'), ('sale', 'Sale'), ('consultation', 'Consultation')], default=1, max_length=20, verbose_name='Type of Appeal'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appeal',
            name='city',
            field=models.CharField(max_length=100, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='estate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appeals', to='estate.estate'),
        ),
    ]
