# Generated by Django 4.2.8 on 2023-12-30 10:43

import apps.city.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': 'Cities'},
        ),
        migrations.AlterField(
            model_name='city',
            name='city_description',
            field=models.TextField(verbose_name='City descriptions'),
        ),
        migrations.AlterField(
            model_name='city',
            name='city_description_ar',
            field=models.TextField(null=True, verbose_name='City descriptions'),
        ),
        migrations.AlterField(
            model_name='city',
            name='city_description_en',
            field=models.TextField(null=True, verbose_name='City descriptions'),
        ),
        migrations.AlterField(
            model_name='city',
            name='city_description_ru',
            field=models.TextField(null=True, verbose_name='City descriptions'),
        ),
        migrations.AlterField(
            model_name='city',
            name='city_description_tr',
            field=models.TextField(null=True, verbose_name='City descriptions'),
        ),
        migrations.AlterField(
            model_name='city',
            name='city_img',
            field=models.ImageField(upload_to=apps.city.models.City.upload_to, verbose_name='City photo'),
        ),
        migrations.AlterField(
            model_name='city',
            name='city_name',
            field=models.CharField(max_length=255, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='city',
            name='city_name_ar',
            field=models.CharField(max_length=255, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='city',
            name='city_name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='city',
            name='city_name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='city',
            name='city_name_tr',
            field=models.CharField(max_length=255, null=True, verbose_name='City'),
        ),
    ]
