# Generated by Django 4.2.8 on 2023-12-30 13:49

import apps.city.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0002_alter_city_options_alter_city_city_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='city_img',
            field=models.ImageField(upload_to=apps.city.models.City.upload_to, verbose_name='City photo preview'),
        ),
        migrations.AlterField(
            model_name='city',
            name='city_name',
            field=models.CharField(max_length=255, unique=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='city',
            name='city_name_ar',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='city',
            name='city_name_en',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='city',
            name='city_name_ru',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='city',
            name='city_name_tr',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='City'),
        ),
    ]
