# Generated by Django 4.2.8 on 2024-01-06 20:38

import apps.city.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0003_alter_city_city_img_alter_city_city_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='city_img',
            field=models.ImageField(upload_to=apps.city.models.City.upload_to, verbose_name='City photo path'),
        ),
    ]
